### ISSUE TITLE
HBuilderX编译成小程序的时候无法使用

### ISSUE THREAD

**Issue by duxingzhe** [sunniejs/vue-canvas-poster#21]
你好，请使用下面的模板创建 issue 以帮助我们更快的排查问题，不规范的 issue 会被关闭，感谢配合。

Browser version [小程序浏览器]
 

vue-canvas-poster version [最新版本]
 

Vue version [2.6]
 

reappear link [无]
 

One-line summary  [使用文档的方式在HbuilderX中引用组件无法实现，只能在浏览器中画海报，小程序无法编译进去提示Cannot read property 'prototype' of undefined]

Other comments [其他信息]

**Comment by duxingzhe** [comment]
不用了，已经使用其他专门适配于小程序的插件，这个问题已经得到了解决。还是感谢提供的插件和方法，就当了解Vue海报插件生成和使用方法。谢谢。

**Comment by SuperZiLu** [comment]
> 不用了，已经使用其他专门适配于小程序的插件，这个问题已经得到了解决。还是感谢提供的插件和方法，就当了解Vue海报插件生成和使用方法。谢谢。

您好 方便告知用的什么插件嘛 我也遇到同样的问题 谢谢

**Comment by duxingzhe** [comment]
在官方的插件市场找的。
